[tool.mypy]
plugins = ["pydantic.mypy"]
mypy_path = "src"
explicit_package_bases = true

[tool.isort]
line_length = 120
known_first_party = ["duty"]
indent = "    "
multi_line_output = 3
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
profile = "black"

[tool.black]
line-length = 120

[tool.flake8]
max-line-length = 120
